version: '0.1'

services:
    app:
        command: streamlit run app/app.py --server.port 8501
        ports:
            - 8501:8501
        image: lukfish/swiss-adt:latest
        environment:
            - OPENAI_API_KEY=$OPENAI_API_KEY